spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/inventories/**
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/orders/**

server:
  port: ${SERVER_PORT:8080}
